import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import StoreProvider from "../(main)/StoreProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const noNavbarRoutes = ['/login', '/signup']

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="ligth">
      <body
        className={cn(`${geistSans.variable} ${geistMono.variable} min-h-screen font-sans grainy antialiased`)}
      >
        <StoreProvider>
          {children}
        </StoreProvider>

      </body>
    </html>
  );
}
